Repository kubernetes-sigs/container-object-storage-interface-csi-adapter, pull requests merged in 2020-12, with the labels that each got.

#6 initial commit for CSI adapter
  .gitignore
  Makefile
  cmd/csi-adapter/cmd.go
  cmd/csi-adapter/driver.go
  cmd/csi-adapter/main.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/identity/identity.go
  pkg/node/node.go
  pkg/node/provisioner.go
  release-tools/.prow.sh
  release-tools/CONTRIBUTING.md
  release-tools/LICENSE
  release-tools/OWNERS
  release-tools/README.md
  release-tools/RELEASE.md
  release-tools/SECURITY_CONTACTS
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/code-of-conduct.md
  release-tools/filter-junit.go
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/update-vendor.sh
  release-tools/util.sh
  release-tools/verify-go-version.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
  release-tools/verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#10 identity: adds GetPluginInfo
  pkg/identity/identity.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#11 Node: initial commits for node server
  go.mod
  pkg/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#9 updated README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
